# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Spreadsheet-WriteExcel-FromDB-Query
version:      0.01
version_from: lib/Spreadsheet/WriteExcel/FromDB/Query.pm
installdirs:  site
requires:
    Spreadsheet::WriteExcel::Simple: 0.02
    Spreadsheet::WriteExcel::FromDB: 1.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
